---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia-deployment
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - name: theia
        image: land007/theia-python:latest
        ports:
        - containerPort: 3000